-- User lifecycle, management history and user-owned triggers.

create table app_private."users" (
  "id" text not null,
  "auth_user_id" uuid,
  "status" text not null,
  "createdAt" bigint not null,
  "status_version" integer default 1 not null,
  "suspended_from" text,
  "account_kind" text generated always as ('USER'::text) stored,
  constraint "users_pkey" PRIMARY KEY (id),
  constraint "users_auth_user_id_key" UNIQUE (auth_user_id),
  constraint "users_status_check" CHECK ((status = ANY (ARRAY['paused'::text, 'active'::text, 'suspended'::text]))),
  constraint "users_status_version_check" CHECK ((status_version > 0)),
  constraint "users_suspended_from_check" CHECK ((suspended_from = ANY (ARRAY['active'::text, 'paused'::text]))),
  constraint "users_auth_user_id_fkey" FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE RESTRICT,
  constraint "users_account_identity_fkey" FOREIGN KEY (id, account_kind) REFERENCES app_private.accounts(id, kind)
);
alter table app_private."users" enable row level security;
revoke all on app_private."users" from public, anon, authenticated, line_app;
grant insert, select, update on app_private."users" to line_app;
create policy "backend" on app_private."users" as permissive for all to "line_app" using (true) with check (true);

-- The existing registration/import path creates the identity in the same transaction.
-- No parallel Account writer or second ID allocation is introduced during expansion.
create function app_private.ensure_user_identity()
returns trigger
language plpgsql
set search_path to 'app_private', 'pg_catalog'
as $function$
begin
  if tg_op = 'DELETE' then
    raise exception 'user_identity_immutable' using errcode = '23514';
  end if;
  if tg_op = 'UPDATE' then
    if new.id is distinct from old.id or new."createdAt" is distinct from old."createdAt" then
      raise exception 'user_identity_immutable' using errcode = '23514';
    end if;
    return new;
  end if;
  insert into app_private.accounts(id, kind, created_at)
    values (new.id, 'USER', new."createdAt") on conflict (id) do nothing;
  if not exists (
    select 1 from app_private.accounts
    where id = new.id and kind = 'USER' and created_at = new."createdAt"
  ) then
    raise exception 'user_identity_mismatch' using errcode = '23514';
  end if;
  return new;
end
$function$;
revoke all on function app_private.ensure_user_identity() from public, anon, authenticated, line_app;
grant execute on function app_private.ensure_user_identity() to line_app;
create trigger user_identity
before insert or update or delete on app_private.users
for each row execute function app_private.ensure_user_identity();

create table app_private."user_events" (
  "id" bigint generated by default as identity not null,
  "user_id" text not null,
  "type" text not null,
  "at" bigint not null,
  constraint "user_events_pkey" PRIMARY KEY (id),
  constraint "user_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES app_private.users(id)
);
CREATE INDEX user_events_user_id ON app_private.user_events USING btree (user_id);
alter table app_private."user_events" enable row level security;
revoke all on app_private."user_events" from public, anon, authenticated, line_app;
grant insert, select on app_private."user_events" to line_app;
create policy "backend" on app_private."user_events" as permissive for all to "line_app" using (true) with check (true);
revoke all on sequence app_private."user_events_id_seq" from public, anon, authenticated, line_app;
grant select, update, usage on sequence app_private."user_events_id_seq" to line_app;

create table app_private."user_management_commands" (
  "actor" text not null,
  "request_id" uuid not null,
  "target" text not null,
  "fingerprint" text not null,
  "action" text not null,
  "reason" text not null,
  "previous_status" text not null,
  "status" text not null,
  "version" integer not null,
  "at" bigint not null,
  "result" jsonb not null,
  constraint "user_management_commands_pkey" PRIMARY KEY (actor, request_id),
  constraint "user_management_commands_action_check" CHECK ((action = ANY (ARRAY['suspend'::text, 'unsuspend'::text]))),
  constraint "user_management_commands_reason_check" CHECK (((length(reason) >= 1) AND (length(reason) <= 500))),
  constraint "user_management_commands_actor_fkey" FOREIGN KEY (actor) REFERENCES app_private.users(id),
  constraint "user_management_commands_target_fkey" FOREIGN KEY (target) REFERENCES app_private.users(id)
);
CREATE INDEX user_management_history ON app_private.user_management_commands USING btree (target, at DESC, request_id);
alter table app_private."user_management_commands" enable row level security;
revoke all on app_private."user_management_commands" from public, anon, authenticated, line_app;
grant insert, select on app_private."user_management_commands" to line_app;
create policy "backend_insert" on app_private."user_management_commands" as permissive for insert to "line_app" with check (true);
create policy "backend_read" on app_private."user_management_commands" as permissive for select to "line_app" using (true);

CREATE OR REPLACE FUNCTION app_private.track_user_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'app_private', 'pg_catalog'
AS $function$
begin
 new.status_version := old.status_version;
 new.suspended_from := old.suspended_from;
 if new.status is distinct from old.status then
  new.status_version := old.status_version+1;
  new.suspended_from := case when new.status='suspended' then old.status else null end;
 end if;
 return new;
end $function$;
revoke all on function app_private."track_user_status"() from public, anon, authenticated, line_app;
grant execute on function app_private."track_user_status"() to line_app;
CREATE TRIGGER user_status_version BEFORE UPDATE ON app_private.users FOR EACH ROW EXECUTE FUNCTION app_private.track_user_status();
