-- Append-only governance command/bootstrap evidence and audit history.

create table app_private.governance_bootstrap_receipts (
  request_id uuid primary key,
  target_kind text not null,
  target_id text not null,
  user_id text not null references app_private.users(id),
  user_status_version integer not null,
  operator_identity text not null,
  database_session_user text not null,
  reason text not null,
  evidence text not null,
  requested_at bigint not null,
  result jsonb not null,
  constraint governance_bootstrap_target_kind_check
    check (target_kind in ('ENTERPRISE', 'ORGANIZATION')),
  constraint governance_bootstrap_user_version_check check (user_status_version > 0),
  constraint governance_bootstrap_operator_check check (length(trim(operator_identity)) > 0),
  constraint governance_bootstrap_session_check check (length(trim(database_session_user)) > 0),
  constraint governance_bootstrap_reason_check check (length(trim(reason)) between 1 and 500),
  constraint governance_bootstrap_evidence_check check (length(trim(evidence)) between 1 and 2000)
);


create table app_private.governance_command_receipts (
  actor_user_id text not null references app_private.users(id),
  request_id uuid not null,
  fingerprint text not null,
  action text not null,
  scope_kind text not null,
  scope_id text not null,
  subject_kind text,
  subject_id text,
  actor_status_version integer not null,
  reason text not null,
  created_at bigint not null,
  result jsonb not null,
  primary key (actor_user_id, request_id),
  constraint governance_command_receipts_fingerprint_check check (fingerprint ~ '^[0-9a-f]{64}$'),
  constraint governance_command_receipts_scope_kind_check
    check (scope_kind in ('enterprise', 'organization', 'organization-team')),
  constraint governance_command_receipts_subject_kind_check
    check (subject_kind is null or subject_kind in ('user', 'organization', 'organization-team', 'enterprise-team')),
  constraint governance_command_receipts_subject_pair_check
    check ((subject_kind is null) = (subject_id is null)),
  constraint governance_command_receipts_actor_version_check check (actor_status_version > 0),
  constraint governance_command_receipts_reason_check check (length(trim(reason)) between 1 and 500)
);


create table app_private.governance_audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id text not null references app_private.users(id),
  actor_status_version integer not null,
  action text not null,
  scope_kind text not null,
  scope_id text not null,
  subject_kind text,
  subject_id text,
  reason text not null,
  request_id uuid not null,
  created_at bigint not null,
  result jsonb not null,
  constraint governance_audit_events_scope_kind_check
    check (scope_kind in ('enterprise', 'organization', 'organization-team')),
  constraint governance_audit_events_subject_kind_check
    check (subject_kind is null or subject_kind in ('user', 'organization', 'organization-team', 'enterprise-team')),
  constraint governance_audit_events_subject_pair_check
    check ((subject_kind is null) = (subject_id is null)),
  constraint governance_audit_events_actor_version_check check (actor_status_version > 0),
  constraint governance_audit_events_reason_check check (length(trim(reason)) between 1 and 500),
  constraint governance_audit_events_request_key unique (actor_user_id, request_id)
);
create index governance_audit_scope_history
  on app_private.governance_audit_events(scope_kind, scope_id, created_at desc, id desc);


create function app_private.reject_governance_history_mutation()
returns trigger
language plpgsql
security invoker
set search_path to 'app_private', 'pg_catalog'
as $function$
begin
  raise exception 'governance_history_immutable' using errcode = '23514';
end
$function$;

create trigger governance_bootstrap_history_immutable
before update or delete on app_private.governance_bootstrap_receipts
for each row execute function app_private.reject_governance_history_mutation();


create trigger governance_command_receipts_immutable
before update or delete on app_private.governance_command_receipts
for each row execute function app_private.reject_governance_history_mutation();

create trigger governance_audit_events_immutable
before update or delete on app_private.governance_audit_events
for each row execute function app_private.reject_governance_history_mutation();

