-- Expense aggregate root.

-- 支出、收據稽核與收件意圖。依賴：User facet。
-- Current desired expenses structure; historical transforms are not replayed here.

create table app_private."expenses" (
  "number" bigint generated by default as identity not null,
  "id" text not null,
  "owner" text not null,
  "scope" text not null,
  "image_id" text not null,
  "body" jsonb not null,
  constraint "expenses_pkey" PRIMARY KEY (number),
  constraint "expenses_id_key" UNIQUE (id),
  constraint "expenses_scope_owner_image_id_key" UNIQUE (scope, owner, image_id),
  constraint "expenses_check" CHECK ((((body ->> 'owner'::text) = owner) AND ((body ->> 'id'::text) = id) AND ((body ->> 'scope'::text) = scope) AND ((body ->> 'imageId'::text) = image_id))),
  constraint "expenses_owner_fkey" FOREIGN KEY (owner) REFERENCES app_private.users(id)
);
CREATE INDEX expenses_owner ON app_private.expenses USING btree (owner);
alter table app_private."expenses" enable row level security;
revoke all on app_private."expenses" from public, anon, authenticated, line_app;
grant delete, insert, select, update on app_private."expenses" to line_app;
create policy "backend" on app_private."expenses" as permissive for all to "line_app" using (true) with check (true);
revoke all on sequence app_private."expenses_number_seq" from public, anon, authenticated, line_app;
grant select, update, usage on sequence app_private."expenses_number_seq" to line_app;
