-- Expense immutable event history.

create table app_private."expense_events" (
  "id" bigint generated by default as identity not null,
  "expense_id" text not null,
  "type" text not null,
  "revision" integer not null,
  "at" bigint not null,
  constraint "expense_events_pkey" PRIMARY KEY (id),
  constraint "expense_events_expense_id_fkey" FOREIGN KEY (expense_id) REFERENCES app_private.expenses(id)
);
CREATE INDEX expense_events_expense ON app_private.expense_events USING btree (expense_id);
alter table app_private."expense_events" enable row level security;
revoke all on app_private."expense_events" from public, anon, authenticated, line_app;
grant insert, select on app_private."expense_events" to line_app;
create policy "backend" on app_private."expense_events" as permissive for all to "line_app" using (true) with check (true);
revoke all on sequence app_private."expense_events_id_seq" from public, anon, authenticated, line_app;
grant select, update, usage on sequence app_private."expense_events_id_seq" to line_app;
