-- Attendance event history.

create table app_private."attendance_events" (
  "id" bigint generated by default as identity not null,
  "uid" text not null,
  "command" text not null,
  "at" bigint not null,
  "recorded_at" bigint not null,
  "details" jsonb not null,
  constraint "attendance_events_pkey" PRIMARY KEY (id),
  constraint "attendance_events_uid_fkey" FOREIGN KEY (uid) REFERENCES app_private.users(id)
);
CREATE INDEX attendance_events_member ON app_private.attendance_events USING btree (uid, at);
CREATE INDEX attendance_events_workplace ON app_private.attendance_events USING btree ((((details -> 'site'::text) ->> 'id'::text)), ((details ->> 'recordId'::text))) WHERE (command = 'clockIn'::text);
alter table app_private."attendance_events" enable row level security;
revoke all on app_private."attendance_events" from public, anon, authenticated, line_app;
grant insert, select on app_private."attendance_events" to line_app;
create policy "backend" on app_private."attendance_events" as permissive for all to "line_app" using (true) with check (true);
revoke all on sequence app_private."attendance_events_id_seq" from public, anon, authenticated, line_app;
grant select, usage on sequence app_private."attendance_events_id_seq" to line_app;
