-- status: reserved
-- owner: workforce
-- scope: versioned EmploymentTerms applicable to an Employment and its compensation/work terms.
-- canonical target: docs/owners/workforce.md
-- migration gate: docs/change/gaps/workforce.md
-- activation: remove reserved status only when a real consumer requires versioned terms and missing/conflict semantics, then add current DDL, data-topology relations, tests, and validation evidence.
