-- status: reserved
-- owner: payroll
-- scope: PayStatement, Earning, Deduction, GrossPay, NetPay, and publication result for Employment + PayPeriod.
-- canonical target: docs/owners/payroll.md
-- migration gate: docs/change/gaps/payroll.md
-- activation: remove reserved status only after deterministic calculation, self-read privacy, publication/correction, authorization, data-topology relations, tests, and validation evidence are current.
